EXP-640 Adicionar rota /pix/keys ao pagarme-js
pagarme/pagarme-js pull request #301
Opened 2021-03-30 17:34 UTC by LucasRichter

## Description

Esse PR adiciona a rota `GET /pix/keys` e `POST /pix/keys`. Com ela, será possivel retornar todas as chaves ativas de uma company no serviço PIX e gerar novas chaves. 

### Como utilizar
- `client.pix.createKey({ recipient_id: 'abc' })`
- `client.pix.getKeys()`

2021-04-01 19:50 UTC, Hrfreire approved these changes

2021-04-01 20:25 UTC, rsmelo approved these changes

2021-04-05 14:32 UTC, rsmelo requested changes
percebi que os metodos estão nomeados de uma forma um pouco diferente dos outros recursos. adiconei a sugestão no review.

Além disso é importante atualizar o jsdoc das novas funções
semelhante ao que temos em `lib/resources/bankAccounts.js`

2021-04-05 14:32 UTC, rsmelo commented on lib/resources/pix.js
> +const createKey = (opts, body) =>
```suggestion
const create = (opts, body) =>
```

sugestão de alterar para manter a consistencia com outros recursos já mapeados

2021-04-05 14:32 UTC, rsmelo commented on lib/resources/pix.js
> +const getKeys = opts =>
```suggestion
const all = opts =>
```

sugestão de alterar para manter a consistencia com outros recursos já mapeados

2021-04-05 15:11 UTC, rsmelo commented
@LucasRichter tava pensando que ao inves de ser `.pix` poderia ser `.pixKeys` para fazer sentido ao `all` e o `create`

2021-04-05 19:52 UTC, rsmelo requested changes

2021-04-05 19:52 UTC, rsmelo commented on lib/resources/pix.js
> + * @name Pix
```suggestion
 * @name Pix keys
```

2021-04-05 19:52 UTC, rsmelo commented on lib/resources/pix.js
> + *              related to the `/pix` path.
```suggestion
 *              related to the `/pix/keys` path.
```

2021-04-05 19:52 UTC, rsmelo commented on lib/resources/pix.js
> +const create = (opts, body) =>
```suggestion
/**
 * `POST /pix/keys`
* Creates a pix key from the given payload
 *
 * @param {Object} opts - An options params which
 *                      is usually already bound
 *                      by `connect` functions.
 *
 * @param {Object} body - The payload for the request.
 * @param  {String} body.recipient_id - The recipient_id assoocietated to the  pix key
 *
 * @returns {Promise} Resolves to the result of
 *                    the request or to an error.
 */
const create = (opts, body) =>
```

só faltou adicionar o comentário na função

2021-04-05 19:52 UTC, rsmelo commented on lib/resources/pix.js
> +const all = opts =>
```suggestion
/**
 * `GET /pix/keys`
* Makes a request to /pix/keys
 *
 * @param {Object} opts - An options params which
 *                      is usually already bound
 *                      by `connect` functions.
 *
 * @returns {Promise} Resolves to the result of
 *                    the request or to an error.
 */
const all = opts =>
```

2021-04-06 12:52 UTC, rsmelo approved these changes

2021-04-06 12:53 UTC, merged