EXP-767 mapear a rota GET /recipients/:recipientId/settlements/contracts
pagarme/pagarme-js pull request #311
Opened 2021-05-27 18:54 UTC by LucasRichter

## Description

Esse PR adiciona a rota de contratos externos nas liquidações. Alteração no rota de `client.settlements()`  para `client.settlements.all()`.

## Como testar
- Verificar se as rotas `client.settlements.all()` está sendo chamado corretamente
- Verificar se as rotas `client.settlements.contracts.all()` está sendo chamado corretamente

2021-05-27 20:11 UTC, diegodsgarcia approved these changes
Por min ta ok! Só esperar semana que vem o deploy no core pra validar os testes que ta show!

2021-05-27 21:01 UTC, Hrfreire approved these changes
Em relação ao código, tá massa. Só não rolou testar a rota ainda pq não tá publicada.

2021-06-01 13:18 UTC, diegodsgarcia requested changes

2021-06-01 13:18 UTC, diegodsgarcia commented on lib/resources/settlements.spec.js
> +    url: '/recipients/abc_123/settlements/contracts ',
Tem um espaço vazio aqui no final da string, fazendo os testes falharem

2021-06-01 17:40 UTC, diegodsgarcia approved these changes

2021-06-01 17:46 UTC, Hrfreire approved these changes

2021-06-01 20:01 UTC, merged